
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-user
    username: root
    password: lixinwei
#  mapper-locations: classpath:com.lixinwei.springboot3demo.mapper.xml/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

